-- =====================================================================
-- Catálogo de Estándares Mínimos · Resolución 0312 de 2019 (Art. 16 y 27)
-- aplica_7: Art. 3 (≤10 trabajadores, riesgo I-III)
-- aplica_21: Art. 9 (11-50 trabajadores, riesgo I-III)
-- Validar la asignación 7/21 contra el texto oficial antes de auditorías.
-- =====================================================================
INSERT INTO api.estandares_0312 (codigo, ciclo, grupo, subgrupo, descripcion, peso, aplica_7, aplica_21, orden) VALUES
('1.1.1','P','Recursos (10%)','Recursos financieros, técnicos, humanos y de otra índole (4%)','Responsable del Sistema de Gestión de Seguridad y Salud en el Trabajo',0.5,true,true,1),
('1.1.2','P','Recursos (10%)','Recursos financieros, técnicos, humanos y de otra índole (4%)','Responsabilidades en el SG-SST asignadas y documentadas',0.5,false,false,2),
('1.1.3','P','Recursos (10%)','Recursos financieros, técnicos, humanos y de otra índole (4%)','Asignación de recursos para el SG-SST',0.5,false,true,3),
('1.1.4','P','Recursos (10%)','Recursos financieros, técnicos, humanos y de otra índole (4%)','Afiliación al Sistema General de Riesgos Laborales',0.5,true,true,4),
('1.1.5','P','Recursos (10%)','Recursos financieros, técnicos, humanos y de otra índole (4%)','Identificación de trabajadores de alto riesgo y cotización de pensión especial (Dec. 2090/2003)',0.5,false,false,5),
('1.1.6','P','Recursos (10%)','Recursos financieros, técnicos, humanos y de otra índole (4%)','Conformación y funcionamiento del COPASST / Vigía',0.5,false,true,6),
('1.1.7','P','Recursos (10%)','Recursos financieros, técnicos, humanos y de otra índole (4%)','Capacitación de los integrantes del COPASST / Vigía',0.5,false,true,7),
('1.1.8','P','Recursos (10%)','Recursos financieros, técnicos, humanos y de otra índole (4%)','Conformación y funcionamiento del Comité de Convivencia Laboral',0.5,false,true,8),
('1.2.1','P','Recursos (10%)','Capacitación en el SG-SST (6%)','Programa de capacitación en promoción y prevención (PyP)',2,true,true,9),
('1.2.2','P','Recursos (10%)','Capacitación en el SG-SST (6%)','Inducción y reinducción en SST, actividades de PyP',2,false,false,10),
('1.2.3','P','Recursos (10%)','Capacitación en el SG-SST (6%)','Responsables del SG-SST con curso virtual de 50 horas',2,false,false,11),
('2.1.1','P','Gestión integral del SG-SST (15%)','Política de SST (1%)','Política del SG-SST firmada, fechada y comunicada al COPASST',1,false,true,12),
('2.2.1','P','Gestión integral del SG-SST (15%)','Objetivos del SG-SST (1%)','Objetivos definidos, claros, medibles, cuantificables, con metas, documentados, revisados',1,false,false,13),
('2.3.1','P','Gestión integral del SG-SST (15%)','Evaluación inicial del SG-SST (1%)','Evaluación e identificación de prioridades',1,false,false,14),
('2.4.1','P','Gestión integral del SG-SST (15%)','Plan anual de trabajo (2%)','Plan que identifica objetivos, metas, responsabilidad, recursos, cronograma, firmado',2,true,true,15),
('2.5.1','P','Gestión integral del SG-SST (15%)','Conservación de la documentación (2%)','Archivo o retención documental del SG-SST',2,false,true,16),
('2.6.1','P','Gestión integral del SG-SST (15%)','Rendición de cuentas (1%)','Rendición sobre el desempeño',1,false,false,17),
('2.7.1','P','Gestión integral del SG-SST (15%)','Normatividad nacional vigente y aplicable en SST (2%)','Matriz legal',2,false,false,18),
('2.8.1','P','Gestión integral del SG-SST (15%)','Comunicación (1%)','Mecanismos de comunicación, auto reporte en SG-SST',1,false,false,19),
('2.9.1','P','Gestión integral del SG-SST (15%)','Adquisiciones (1%)','Identificación, evaluación para adquisición de productos y servicios en SG-SST',1,false,false,20),
('2.10.1','P','Gestión integral del SG-SST (15%)','Contratación (2%)','Evaluación y selección de proveedores y contratistas',2,false,false,21),
('2.11.1','P','Gestión integral del SG-SST (15%)','Gestión del cambio (1%)','Evaluación del impacto de cambios internos y externos en el SG-SST',1,false,false,22),
('3.1.1','H','Gestión de la salud (20%)','Condiciones de salud en el trabajo (9%)','Evaluación médica ocupacional: descripción sociodemográfica y diagnóstico de condiciones de salud',1,false,true,23),
('3.1.2','H','Gestión de la salud (20%)','Condiciones de salud en el trabajo (9%)','Actividades de promoción y prevención en salud',1,false,true,24),
('3.1.3','H','Gestión de la salud (20%)','Condiciones de salud en el trabajo (9%)','Información al médico de los perfiles de cargo',1,false,false,25),
('3.1.4','H','Gestión de la salud (20%)','Condiciones de salud en el trabajo (9%)','Realización de evaluaciones médicas ocupacionales: peligros, periodicidad, comunicación al trabajador',1,true,true,26),
('3.1.5','H','Gestión de la salud (20%)','Condiciones de salud en el trabajo (9%)','Custodia de historias clínicas',1,false,false,27),
('3.1.6','H','Gestión de la salud (20%)','Condiciones de salud en el trabajo (9%)','Restricciones y recomendaciones médico-laborales',1,false,true,28),
('3.1.7','H','Gestión de la salud (20%)','Condiciones de salud en el trabajo (9%)','Estilos de vida y entornos saludables (tabaquismo, alcoholismo, farmacodependencia, otros)',1,false,false,29),
('3.1.8','H','Gestión de la salud (20%)','Condiciones de salud en el trabajo (9%)','Agua potable, servicios sanitarios y disposición de basuras',1,false,false,30),
('3.1.9','H','Gestión de la salud (20%)','Condiciones de salud en el trabajo (9%)','Eliminación adecuada de residuos sólidos, líquidos o gaseosos',1,false,false,31),
('3.2.1','H','Gestión de la salud (20%)','Registro, reporte e investigación de EL, incidentes y AT (5%)','Reporte de accidentes de trabajo y enfermedad laboral a la ARL, EPS y Dirección Territorial del Ministerio de Trabajo',2,false,true,32),
('3.2.2','H','Gestión de la salud (20%)','Registro, reporte e investigación de EL, incidentes y AT (5%)','Investigación de incidentes, accidentes de trabajo y enfermedades cuando sean diagnosticadas como laborales',2,false,true,33),
('3.2.3','H','Gestión de la salud (20%)','Registro, reporte e investigación de EL, incidentes y AT (5%)','Registro y análisis estadístico de incidentes, accidentes de trabajo y enfermedad laboral',1,false,false,34),
('3.3.1','H','Gestión de la salud (20%)','Mecanismos de vigilancia de las condiciones de salud (6%)','Medición de la severidad de los accidentes de trabajo y enfermedad laboral',1,false,false,35),
('3.3.2','H','Gestión de la salud (20%)','Mecanismos de vigilancia de las condiciones de salud (6%)','Medición de la frecuencia de los incidentes, accidentes de trabajo y enfermedad laboral',1,false,false,36),
('3.3.3','H','Gestión de la salud (20%)','Mecanismos de vigilancia de las condiciones de salud (6%)','Medición de la mortalidad de accidentes de trabajo y enfermedad laboral',1,false,false,37),
('3.3.4','H','Gestión de la salud (20%)','Mecanismos de vigilancia de las condiciones de salud (6%)','Medición de la prevalencia de incidentes, accidentes de trabajo y enfermedad laboral',1,false,false,38),
('3.3.5','H','Gestión de la salud (20%)','Mecanismos de vigilancia de las condiciones de salud (6%)','Medición de la incidencia de incidentes, accidentes de trabajo y enfermedad laboral',1,false,false,39),
('3.3.6','H','Gestión de la salud (20%)','Mecanismos de vigilancia de las condiciones de salud (6%)','Medición del ausentismo por incidentes, accidentes de trabajo y enfermedad laboral',1,false,false,40),
('4.1.1','H','Gestión de peligros y riesgos (30%)','Identificación de peligros, evaluación y valoración de riesgos (15%)','Metodología para la identificación de peligros, evaluación y valoración de los riesgos',4,false,false,41),
('4.1.2','H','Gestión de peligros y riesgos (30%)','Identificación de peligros, evaluación y valoración de riesgos (15%)','Identificación de peligros con participación de todos los niveles de la empresa',4,true,true,42),
('4.1.3','H','Gestión de peligros y riesgos (30%)','Identificación de peligros, evaluación y valoración de riesgos (15%)','Identificación y priorización de la naturaleza de los peligros (metodología adicional, cancerígenos y otros)',3,false,false,43),
('4.1.4','H','Gestión de peligros y riesgos (30%)','Identificación de peligros, evaluación y valoración de riesgos (15%)','Realización de mediciones ambientales, químicos, físicos y biológicos',4,false,false,44),
('4.2.1','H','Gestión de peligros y riesgos (30%)','Medidas de prevención y control para intervenir los peligros/riesgos (15%)','Se implementan las medidas de prevención y control de peligros/riesgos identificados',2.5,true,true,45),
('4.2.2','H','Gestión de peligros y riesgos (30%)','Medidas de prevención y control para intervenir los peligros/riesgos (15%)','Se verifica aplicación de las medidas de prevención y control por parte de los trabajadores',2.5,false,false,46),
('4.2.3','H','Gestión de peligros y riesgos (30%)','Medidas de prevención y control para intervenir los peligros/riesgos (15%)','Hay procedimientos, instructivos, fichas, protocolos',2.5,false,false,47),
('4.2.4','H','Gestión de peligros y riesgos (30%)','Medidas de prevención y control para intervenir los peligros/riesgos (15%)','Inspección con el COPASST o Vigía',2.5,false,false,48),
('4.2.5','H','Gestión de peligros y riesgos (30%)','Medidas de prevención y control para intervenir los peligros/riesgos (15%)','Mantenimiento periódico de instalaciones, equipos, máquinas, herramientas',2.5,false,true,49),
('4.2.6','H','Gestión de peligros y riesgos (30%)','Medidas de prevención y control para intervenir los peligros/riesgos (15%)','Entrega de Elementos de Protección Personal (EPP), se verifica con contratistas y subcontratistas',2.5,false,true,50),
('5.1.1','H','Gestión de amenazas (10%)','Plan de prevención, preparación y respuesta ante emergencias (10%)','Se cuenta con el Plan de Prevención, Preparación y Respuesta ante emergencias',5,false,true,51),
('5.1.2','H','Gestión de amenazas (10%)','Plan de prevención, preparación y respuesta ante emergencias (10%)','Brigada de prevención conformada, capacitada y dotada',5,false,false,52),
('6.1.1','V','Verificación del SG-SST (5%)','Gestión y resultados del SG-SST (5%)','Indicadores de estructura, proceso y resultado',1.25,false,false,53),
('6.1.2','V','Verificación del SG-SST (5%)','Gestión y resultados del SG-SST (5%)','Las empresas adelantan auditoría por lo menos una vez al año',1.25,false,false,54),
('6.1.3','V','Verificación del SG-SST (5%)','Gestión y resultados del SG-SST (5%)','Revisión anual de la alta dirección, resultados y alcance de la auditoría',1.25,false,false,55),
('6.1.4','V','Verificación del SG-SST (5%)','Gestión y resultados del SG-SST (5%)','Planificación de auditorías con el COPASST',1.25,false,false,56),
('7.1.1','A','Mejoramiento (10%)','Acciones preventivas y correctivas con base en los resultados del SG-SST (10%)','Definición de acciones preventivas y correctivas con base en resultados del SG-SST',2.5,false,false,57),
('7.1.2','A','Mejoramiento (10%)','Acciones preventivas y correctivas con base en los resultados del SG-SST (10%)','Acciones de mejora conforme a revisión de la alta dirección',2.5,false,false,58),
('7.1.3','A','Mejoramiento (10%)','Acciones preventivas y correctivas con base en los resultados del SG-SST (10%)','Acciones de mejora con base en investigaciones de accidentes de trabajo y enfermedades laborales',2.5,false,false,59),
('7.1.4','A','Mejoramiento (10%)','Acciones preventivas y correctivas con base en los resultados del SG-SST (10%)','Elaboración del plan de mejoramiento e implementación de medidas y acciones correctivas solicitadas por autoridades y ARL',2.5,false,false,60);

-- =====================================================================
-- Catálogo normativo base para la matriz legal.
-- Punto de partida: cada empresa debe verificar vigencia y aplicabilidad.
-- =====================================================================
INSERT INTO api.normativa (tipo, numero, anio, emisor, tema, requisito, aplica) VALUES
('Ley','9',1979,'Congreso de la República','Código Sanitario Nacional','Título III: condiciones de salud ocupacional en los lugares de trabajo','Todas las empresas'),
('Resolución','2400',1979,'Ministerio de Trabajo','Estatuto de seguridad industrial','Condiciones de vivienda, higiene y seguridad en los establecimientos de trabajo','Todas las empresas'),
('Resolución','2013',1986,'Ministerios de Trabajo y Salud','COPASST','Organización y funcionamiento del COPASST; reunión mínima mensual','Empresas con 10 o más trabajadores (vigía si son menos)'),
('Decreto','1295',1994,'Presidencia de la República','Sistema General de Riesgos Laborales','Afiliación, cotización y reporte de AT/EL a ARL y EPS dentro de los 2 días hábiles siguientes','Todas las empresas'),
('Ley','776',2002,'Congreso de la República','Prestaciones del SGRL','Reubicación y reincorporación del trabajador tras incapacidad','Todas las empresas'),
('Decreto','2090',2003,'Presidencia de la República','Actividades de alto riesgo','Identificar trabajadores en actividades de alto riesgo y cotizar puntos adicionales de pensión','Empresas con actividades de alto riesgo'),
('Ley','1010',2006,'Congreso de la República','Acoso laboral','Mecanismos de prevención y procedimiento interno confidencial','Todas las empresas'),
('Resolución','1401',2007,'Ministerio de la Protección Social','Investigación de incidentes y accidentes','Investigar dentro de los 15 días siguientes; equipo investigador con jefe inmediato, COPASST y responsable SST','Todas las empresas'),
('Resolución','2646',2008,'Ministerio de la Protección Social','Riesgo psicosocial','Identificación, evaluación, prevención e intervención de factores de riesgo psicosocial','Todas las empresas'),
('Ley','1221',2008,'Congreso de la República','Teletrabajo','Obligaciones de SST para teletrabajadores','Empresas con teletrabajadores'),
('Resolución','652',2012,'Ministerio de Trabajo','Comité de Convivencia Laboral','Conformación, funcionamiento y reuniones trimestrales (modificada por Res. 1356/2012)','Todas las empresas'),
('Ley','1562',2012,'Congreso de la República','Sistema de Riesgos Laborales','Definiciones de AT y EL; SG-SST obligatorio; afiliación de contratistas','Todas las empresas'),
('Ley','1523',2012,'Congreso de la República','Gestión del riesgo de desastres','Análisis de riesgo, planes de contingencia y respuesta a emergencias','Todas las empresas'),
('Decreto','723',2013,'Ministerio de Trabajo','Afiliación de contratistas','Afiliación al SGRL de contratistas con contrato superior a un mes','Empresas con contratistas'),
('Ley','1616',2013,'Congreso de la República','Salud mental','Promoción de la salud mental y prevención del trastorno mental en el ámbito laboral','Todas las empresas'),
('Decreto','1477',2014,'Ministerio de Trabajo','Tabla de enfermedades laborales','Referencia para la identificación y calificación de enfermedades laborales','Todas las empresas'),
('Decreto','1072',2015,'Ministerio de Trabajo','Decreto Único Reglamentario del Sector Trabajo','Libro 2, Parte 2, Título 4, Capítulo 6: diseño, implementación y mejora continua del SG-SST (ciclo PHVA)','Todas las empresas'),
('Decreto','1072',2015,'Ministerio de Trabajo','Conservación documental','Art. 2.2.4.6.13: conservar registros del SG-SST mínimo 20 años desde el cese de la relación laboral','Todas las empresas'),
('Decreto','472',2015,'Ministerio de Trabajo','Sanciones SST','Criterios de graduación de multas por incumplimiento de normas de SST','Todas las empresas'),
('Resolución','4927',2016,'Ministerio de Trabajo','Curso virtual de 50 horas','Responsable del SG-SST con curso de 50 horas y actualización de 20 horas cada 3 años','Todas las empresas'),
('Decreto','2157',2017,'Presidencia de la República','PGRDEPP','Plan de gestión del riesgo de desastres de entidades públicas y privadas','Según actividad y nivel de riesgo'),
('Resolución','0312',2019,'Ministerio de Trabajo','Estándares Mínimos del SG-SST','Autoevaluación anual, plan de mejoramiento y reporte a la ARL/Ministerio; indicadores del Art. 30','Todas las empresas'),
('Resolución','5018',2019,'Ministerio de Trabajo','Sector eléctrico','Lineamientos de SST en procesos de generación, transmisión, distribución y comercialización','Sector eléctrico'),
('Resolución','0491',2020,'Ministerio de Trabajo','Espacios confinados','Requisitos mínimos de seguridad para trabajo en espacios confinados','Empresas con trabajo en espacios confinados'),
('Ley','2050',2020,'Congreso de la República','Plan Estratégico de Seguridad Vial','Diseño e implementación del PESV','Empresas con flota según umbrales legales'),
('Resolución','4272',2021,'Ministerio de Trabajo','Trabajo en alturas','Requisitos mínimos de seguridad para trabajo en alturas (deroga Res. 1409/2012)','Empresas con trabajo en alturas (≥ 2 m)'),
('Resolución','0773',2021,'Ministerio de Trabajo','Sistema Globalmente Armonizado (SGA)','Clasificación, etiquetado y fichas de datos de seguridad de productos químicos','Empresas que usan productos químicos'),
('Resolución','0754',2021,'Ministerio de Salud','Licencias de SST','Procedimiento de expedición y renovación de licencias de SST','Profesionales y empresas prestadoras de servicios SST'),
('Ley','2088',2021,'Congreso de la República','Trabajo en casa','Garantías de SST durante el trabajo en casa','Empresas con trabajo en casa'),
('Ley','2121',2021,'Congreso de la República','Trabajo remoto','Obligaciones de SST en trabajo remoto','Empresas con trabajo remoto'),
('Ley','2191',2022,'Congreso de la República','Desconexión laboral','Política de desconexión laboral','Todas las empresas'),
('Resolución','2764',2022,'Ministerio de Trabajo','Batería de riesgo psicosocial','Aplicación de la batería: anual si el riesgo es alto, cada dos años si es medio o bajo','Todas las empresas'),
('Resolución','40595',2022,'Ministerio de Transporte','Metodología PESV','Metodología para el diseño, implementación y verificación del PESV','Empresas obligadas al PESV'),
('Ley','2365',2024,'Congreso de la República','Acoso sexual en el ámbito laboral','Medidas de prevención, protección y atención del acoso sexual laboral','Todas las empresas'),
('Resolución','1843',2025,'Ministerio de Trabajo','Evaluaciones médicas ocupacionales','Evaluaciones médicas ocupacionales e historias clínicas (reemplaza Res. 2346/2007 y 1918/2009; revisar régimen de transición)','Todas las empresas'),
('Ley','2466',2025,'Congreso de la República','Reforma laboral','Revisar disposiciones con impacto en SST, jornada y afiliación a riesgos laborales','Todas las empresas'),
('Guía técnica','GTC 45',2012,'ICONTEC','Identificación de peligros','Metodología de identificación de peligros y valoración de riesgos','Referencia técnica');
